title: Cesarine Graham
logo: /assets/headshot.jpg
description: Hello! I'm Cesarine (Sez-A-Reen) and I am interested in theoretical physics / computational physics.
#logo: /assets/knott.png
show_downloads: false
theme: jekyll-theme-minimal
