title: Cesarine Graham
logo: /assets/headshot.jpg
description: Hello! I'm Cesarine Graham (Sez-A-Reen), formally known as Cesarine Aylsworth, and I am interested in theoretical physics / computational physics. In my free time, I am usually outdoors hiking or fishing, but I also enjoy powerlifting, yoga, and reading.

# --- List of links in the navigation bar --- #

author:
  name   : "Jan Meppe"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Machine learning engineer in love with building digital products."
  location : "Amsterdam"
  links:
    - label: "Resume"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/cesarinegraham/assets/graham_resume.pdf"

show_downloads: false
theme: jekyll-theme-minimal
