title: Cesarine Graham
logo: /assets/headshot.jpg
description: Hello! I'm Cesarine Graham (Sez-A-Reen), and I am passionate about contributing to the space industry, with a particular focus on supporting NASA's Artemis mission and advancing lunar exploration. In my free time, I am usually outdoors hiking or fishing, but I also enjoy powerlifting, yoga, and reading.

show_downloads: false
theme: jekyll-theme-minimal
