title: Cesarine Graham
logo: /assets/headshot.jpg
description: Hello! I'm Cesarine (Sez-A-Reen) and I am interested in theoretical physics / computational physics.
show_downloads: true
theme: jekyll-theme-minimal
