title: Cesarine Graham
logo: /assets/headshot.jpg
description: Hello! I'm Cesarine Graham (Sez-A-Reen), formally known as Cesarine Aylsworth, and I am interested in theoretical physics / computational physics. In my free time, I am usually outdoors hiking or fishing, but I also enjoy powerlifting, yoga, and reading.
You can download my resume [here](https://github.com/cesarinegraham/assets/graham_resume.pdf).

#logo: /assets/knott.png

show_downloads: false
theme: jekyll-theme-minimal
