baseURL: "https://cesarinegraham.github.io/cgraham.github.io/"
title: césarine graham
theme:  PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: about
      url: about/
      weight: 1
    - name: news
      url: posts/
      weight: 2
    - name: cv
      url: cv/
      weight: 3
    - name: research
      url: research/
      weight: 4
    - name: pubs
      url: pubs/
      weight: 4.5
    - name: teaching
      url: teaching/
      weight: 5

params:
  description: "This website hosts Césarine Graham's research papers, current work, curriculum vitae, and contact information."
  author: césarine graham
  DateFormat: "January 2006"
  defaultTheme: dark
  hideFooter: true
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: true
  disableAnchoredHeadings: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  MainSections: ["posts"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: true
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: césarine graham
    subtitle: |
      <ul>
      <b>im a graduate student in the <a href="https://sciences.ucf.edu/physics/" target="_blank" rel="noopener" aria-label="department of physics and planetary sciences(opens in new tab)"><u>department of physics and planetary sciences</u></a> at the university of central florida. </b>
    
    imageUrl: "/img/headshot.png"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: about
        url: about/
      - name: news
        url: posts/
      - name: cv
        url: cv/
      - name: research
        url: research/
      - name: pubs
        url: pubs/

  socialIcons:
    - name: Email
      url: mailto:ce970069@ucf.edu
    - name: Google Scholar
      url: https://scholar.google.com/citations?hl=en&user=KdrjfscAAAAJ
    - name: ORCID
      url: https://orcid.org/0009-0007-1047-8146
    - name: GitHub
      url: https://github.com/cesarinegraham

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "césarine graham"
    icon: favicon-32x32.png
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
